version: 0
allowPullRequests: collaborators
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    routes:
      - index.garbage.condprof
    extra:
      github:
        events:
          - push
        branches:
          - master
    payload:
      maxRunTime: 3600
      image: tarekziade/condprof
      command:
          - "/bin/bash"
          - "-c"
          - >-
            git clone --quiet https://github.com/tarekziade/conditioned-profile &&
            cd heavy-profile &&
            pip install --quiet --upgrade -r requirements.txt &&
            python setup.py develop &&
            hp-creator --max-urls 115 /app/profile &&
            hp-archiver /app/profile /app/archives
      artifacts:
        public:
          type: 'directory'
          path: '/app/archives'
    metadata:
      name: CondProfile
      description: Conditioned Profile Generator
      owner: tarek@ziade.org
      source: https://github.com/tarekziade/conditioned-profile
